language: node_js
node_js:
  - "v10.16.3"
branches:
  only:
    - master    # 构建的分支
cache:
  directories:
    - node_modules # 依赖缓存的目录
before_install:
  - export TZ='Asia/Shanghai'  # 设置时区
install:
  npm install
  #- npm install -g gitbook-cli # 安装编译工具
script:
  - npm run build
  #- gitbook build
after_script:
  - cd ./build
  - git init
  - git config user.name "KAM" # 修改name
  - git config user.email "1479376017@qq.com" # 修改email
  - git add .
  - git commit -m "Travis CI Auto Builder"
  - git push origin travis # GH_TOKEN是在Travis中配置token的名称
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN # github 上的token环境变量
  local-dir: ./build/ # 根据情况自定义到静态文件输出目录
  keep_history: true
  skip-cleanup: true
  #verbose: true
  on:
    branch: master

